// angularAssignment/src/app/addplay/addplay.component.ts
import { Component, OnInit, Input, Output, EventEmitter} from '@angular/core';
import { ControlsService } from '../controls/controls.service';

@Component({
  selector: 'app-addplay',
  templateUrl: './addplay.component.html',
  styleUrls: ['./addplay.component.css']
})
export class AddPlayComponent implements OnInit {
  videoList:any;
  video:any;
  videoNo:any;
  videoName:any;
  videoUrl:any;
  id:any;

  constructor(private controlsService: ControlsService) { }

  ngOnInit() {

    this.video = {};

    this.videoNo = "1";

    this.id = 1;

    this.getData();

  }

  getData(){
    this.controlsService.getAddData().then((res) => {
      this.videoList = res;
      for(let i=0; i<this.videoList.length; i++){
        this.videoList[i].noEditorTitle = true;
        this.videoList[i].noEditorUrl = true;
      }
      this.videoNo = (this.videoList.length+1).toString();
      this.id = this.videoList.length+1;
    });
  }

  add(){
    var reg = /^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\*\+,;=.]+$/;
    var validation = reg.test(this.videoUrl);
    if(validation){
      this.video.videoNo = this.videoNo;
      this.video.approved = false;
      this.video.videoName = this.videoName;
      this.video.videoUrl = this.videoUrl;
      this.controlsService.addAddData(this.video);
    }else{
      alert("please check if the url is correct!");
    }

  }

  delete(id){
    this.controlsService.deleteData(id).then((res) => {
      console.log(res);
    });
  }

  editor(id){
    for(let i =0;i<this.videoList.length;i++){
       if(this.videoList[i].id == id){
         if(this.videoList[i].noEditorTitle == false || this.videoList[i].noEditorUrl == false){
            this.videoList[i].approved = false;
            this.controlsService.editorAddData(id,this.videoList[i]);
        }else{
            alert("please click title or url input if you want to edit them");
        }
      }
    }
  }

  approve(id){
      for(let i =0;i<this.videoList.length;i++){
          if(this.videoList[i].id == id){
            this.videoList[i].approved = true;
            this.controlsService.approveAddData(id,this.videoList[i]);
           }
       }
  }

  canEditor(id){
    for(let i =0;i<this.videoList.length;i++){
      if(this.videoList[i].id == id){
        this.videoList[i].noEditorTitle = false;
        this.videoList[i].noEditorUrl = false;
      }
    }
  }

}

<div class="row">
        <div class="col-lg-6">
          <div class="input-group">
            <span class="">
              Title:
            </span>&nbsp;&nbsp;
            <input type="text" class="form-control" name="videoName" [(ngModel)]="videoName" >
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
    </div><!-- /.row -->
    <br>
    <div class="row">
        <div class="col-lg-6">
          <div class="input-group">
            <span class="">
               URL:
            </span>&nbsp;&nbsp;
            <input type="text" class="form-control" name="videoUrl" [(ngModel)]="videoUrl">
            <br>
          </div><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
</div><!-- /.row -->
<div class="row"><br></div>
<div class="row">
<span class="input-group-btn">
        <button class="btn btn-primary" type="button" (click)="add()">Add Video</button>
</span>
</div>
<br>
<div>
    <table class="table table-bordered">
        <thead>
            <tr>
            <th>NO</th>
            <th>title</th>
            <th>url</th>
            <th colspan="3">Operation</th>
            </tr>
        </thead>
        <tbody *ngFor="let item of videoList;let i=index">
            <tr>
                <td>{{item.videoNo}}</td>
                <td (click)="canEditor(item.id)"><input type="text" class="form-control" [(ngModel)]="item.videoName" [disabled]="item.noEditorTitle"></td>
                <td (click)="canEditor(item.id)"><input type="url" class="form-control" [(ngModel)]="item.videoUrl" [disabled]="item.noEditorUrl" ></td>
                <td ><button class="btn btn-primary" type="button" (click)="editor(item.id)">Edit</button></td>
                <td><button class="btn btn-primary" type="button" (click)="delete(item.id)">Delete</button></td>
                <td><button class="btn btn-primary" type="button" (click)="approve(item.id)"  [ngClass]="{'disabled': item.approved}" >Approve</button></td>
            </tr>
        </tbody>
    </table>
</div>

// react-assignment/src/addplay/Addplay.js
import React, { Component } from 'react';
import './Addplay.css';

class Addplay extends Component{

  constructor(props) {
    super(props);
    this.state={
      videoNo:'1',
      list:{},
    }
  }

  componentDidMount(){
    this.getData();
  }

  getData(){
    fetch('http://localhost:3003/videoList', {
      method: "GET",
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
        },
    })
    .then(response => response.json())
    .then(data => {
      console.log("logs");
      this.setState({
        list: data
      });
    })
  }

  add(){
    fetch('http://localhost:3003/getMockData', {
      method: "GET",
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
        },
    })
    .then(response => response.json())
    .then(data => {
      console.log(data);
    })
    var reg = /^(?:http(s)?:\/\/)?[\w.-]+(?:\.[\w\.-]+)+[\w\-\._~:/?#[\]@!\$&'\*\+,;=.]+$/;
    var validation = reg.test(this.videoUrl);
    if(validation){
      this.video.videoNo = this.state.videoNo;
      this.video.approved = false;
      this.video.videoName = this.videoName;
      this.video.videoUrl = this.videoUrl;
      this.controlsService.addAddData(this.video);
    }else{
      alert("please check if the url is correct!");
    }

  }

  render(){
    console.log(this.state.list);
    return(
<div className="container">
<div className="row">
        <div className="col-lg-6">
          <div className="input-group">
            <span className="">
              Title:
            </span>&nbsp;&nbsp;
            <input type="text" className="form-control" name="videoName" />
          </div>
        </div>
  </div>
    <div className="row">
        <div className="col-lg-6">
          <div className="input-group">
            <span className="">
               URL:
            </span>&nbsp;&nbsp;
            <input type="text" className="form-control" name="videoUrl" ref="videoUrl"/>
          </div>
      </div>
</div>
<div className="row"></div>
{<br />}
<div className="row">
<span className="input-group-btn">
        <button className="btn btn-primary" type="button"onClick={()=>this.add()} >Add Video</button>
</span>
</div>
{<br />}
<div id="table-list">
    <table className="table table-bordered">
        <thead>
            <tr>
            <th>NO</th>
            <th>title</th>
            <th>url</th>
            <th colSpan="3">Operation</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
</div>
)
}
}

export default Addplay;




                {  
                  (this.state.list.length==0)
                  ?null
                  :this.state.list((item,index)=>{
                   return (
                    <tr>
                    <td>{item["videoName"]}</td>
                    <td ><input type="text" className="form-control" /></td>
                    <td ><input type="url" className="form-control" value={this.state.videoPath}/></td>
                    <td ><button className="btn btn-primary" type="button" >Edit</button></td>
                    <td><button className="btn btn-primary" type="button" >Delete</button></td>
                    <td><button className="btn btn-primary" type="button">Approve</button></td>
                    </tr>
                    )
                    },this)
                    }
